[2025-09-29 06:38:58,961: INFO: main: Welcome to our custom log]
[2025-09-30 01:38:56,604: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 01:38:56,610: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 01:42:20,537: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 01:42:20,546: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 01:48:17,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 01:48:17,777: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 02:00:44,626: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 02:00:44,635: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 02:01:32,068: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 02:01:32,074: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 02:01:50,313: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 02:01:50,320: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 07:38:03,995: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 07:38:04,005: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 07:47:05,065: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 07:47:05,073: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 07:47:48,661: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 07:47:48,667: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 07:48:25,486: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 07:48:25,492: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 07:50:43,784: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 07:50:43,791: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 08:08:28,653: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 08:08:28,726: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 08:08:28,734: INFO: common: created directory at: artifacts]
[2025-09-30 08:08:28,740: INFO: common: created directory at: artifacts/data_ingestion]
[2025-09-30 08:08:28,757: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-09-30 08:08:48,386: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-09-30 12:25:07,001: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-09-30 12:25:07,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 12:25:07,042: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 12:25:07,044: INFO: common: created directory at: artifacts]
[2025-09-30 12:25:07,046: INFO: common: created directory at: artifacts/data_ingestion]
[2025-09-30 12:25:07,050: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-09-30 12:25:35,574: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-09-30 12:25:37,957: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-09-30 12:29:40,913: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-09-30 12:29:40,918: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-09-30 12:29:40,927: INFO: common: yaml file: params.yaml loaded successfully]
[2025-09-30 12:29:40,931: INFO: common: created directory at: artifacts]
[2025-09-30 12:29:40,934: INFO: common: created directory at: artifacts/data_ingestion]
[2025-09-30 12:29:40,936: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-09-30 12:29:59,415: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-09-30 12:30:07,416: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-02 07:18:54,905: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-02 07:18:54,991: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-02 07:18:54,998: INFO: common: created directory at: artifacts]
[2025-10-02 07:18:55,007: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-02 13:22:07,380: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-02 13:22:07,688: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-02 13:22:07,700: INFO: common: created directory at: artifacts]
[2025-10-02 13:22:07,705: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-02 13:32:24,225: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-02 13:32:24,242: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-02 13:32:24,248: INFO: common: created directory at: artifacts]
[2025-10-02 13:32:24,254: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-02 13:32:43,502: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-02 14:02:41,926: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-02 14:02:41,934: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-02 14:02:41,942: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-02 14:02:41,944: INFO: common: created directory at: artifacts]
[2025-10-02 14:02:41,945: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 10, in <module>
    obj.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_pipeline.py", line 12, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2025-10-02 14:12:39,570: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-02 14:12:39,577: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-02 14:12:39,586: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-02 14:12:39,588: INFO: common: created directory at: artifacts]
[2025-10-02 14:12:39,589: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-02 14:12:39,591: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-02 14:12:58,510: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-02 14:13:01,017: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-02 14:13:01,020: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-02 14:13:01,028: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-02 14:13:01,037: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-02 14:13:01,040: INFO: common: created directory at: artifacts]
[2025-10-02 14:13:01,042: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-02 14:13:03,315: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-02 14:13:04,847: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-04 08:45:38,075: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 08:45:38,110: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 08:55:33,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 08:55:33,361: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 08:55:33,367: INFO: common: created directory at: artifacts]
[2025-10-04 08:55:33,371: INFO: common: created directory at: artifacts\model_training]
[2025-10-04 08:59:06,308: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 08:59:06,318: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 08:59:06,323: INFO: common: created directory at: artifacts]
[2025-10-04 08:59:06,329: INFO: common: created directory at: artifacts\model_training]
[2025-10-04 09:06:43,369: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 09:06:43,379: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 09:06:43,385: INFO: common: created directory at: artifacts]
[2025-10-04 09:06:43,390: INFO: common: created directory at: artifacts\model_training]
[2025-10-04 09:21:32,907: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-04 09:21:36,698: INFO: builder_impl: Assets written to: artifacts\model_training\assets]
[2025-10-04 09:45:31,543: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-04 09:45:31,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 09:45:31,559: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 09:45:31,584: INFO: common: created directory at: artifacts]
[2025-10-04 09:45:31,590: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-04 09:45:31,597: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-04 09:45:54,914: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-04 09:45:57,565: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-04 09:45:57,583: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-04 09:45:57,594: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 09:45:57,609: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 09:45:57,684: INFO: common: created directory at: artifacts]
[2025-10-04 09:45:57,719: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-04 09:46:01,160: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-04 09:46:02,387: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-04 09:46:02,391: INFO: main: *******************]
[2025-10-04 09:46:02,399: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-04 09:46:02,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 09:46:02,419: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 09:46:02,422: INFO: common: created directory at: artifacts]
[2025-10-04 09:46:02,423: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 35, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_03_pipeline.py", line 11, in main
    training_config = config.get_training_config()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\config\configuration.py", line 56, in get_training_config
    training_data=os.path.join(self.config.data_ingestion.unzip_dir,"kidney-ct-scan-image")
                  ^^
NameError: name 'os' is not defined
[2025-10-04 09:47:11,716: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-04 09:47:11,724: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 09:47:11,731: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 09:47:11,733: INFO: common: created directory at: artifacts]
[2025-10-04 09:47:11,734: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-04 09:47:11,736: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-04 09:47:35,485: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-04 09:47:37,674: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-04 09:47:37,676: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-04 09:47:37,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 09:47:37,693: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 09:47:37,696: INFO: common: created directory at: artifacts]
[2025-10-04 09:47:37,699: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-04 09:47:39,534: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-04 09:47:40,479: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-04 09:47:40,480: INFO: main: *******************]
[2025-10-04 09:47:40,481: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-04 09:47:40,488: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 09:47:40,497: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 09:47:40,511: INFO: common: created directory at: artifacts]
[2025-10-04 09:47:40,513: INFO: common: created directory at: artifacts\model_training]
[2025-10-04 09:59:42,912: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-04 09:59:48,775: INFO: builder_impl: Assets written to: artifacts\model_training\assets]
[2025-10-04 09:59:49,034: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-07 20:04:53,442: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-07 20:04:53,462: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 20:04:53,498: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 20:04:53,514: INFO: common: created directory at: artifacts]
[2025-10-07 20:04:53,517: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 20:04:53,522: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-07 20:07:22,165: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-07 20:07:25,456: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-07 20:07:25,471: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-07 20:07:25,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 20:07:25,503: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 20:07:25,510: INFO: common: created directory at: artifacts]
[2025-10-07 20:07:25,513: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 20:07:28,364: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 20:07:30,744: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-07 20:07:30,745: INFO: main: *******************]
[2025-10-07 20:07:30,746: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-07 20:07:30,754: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 20:07:30,760: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 20:07:30,762: INFO: common: created directory at: artifacts]
[2025-10-07 20:07:30,764: INFO: common: created directory at: artifacts\training]
[2025-10-07 20:26:35,722: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-07 20:26:42,129: INFO: builder_impl: Assets written to: artifacts\training\assets]
[2025-10-07 20:26:44,400: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-07 21:14:00,436: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-07 21:14:00,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 21:14:00,463: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 21:14:00,467: INFO: common: created directory at: artifacts]
[2025-10-07 21:14:00,469: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 21:14:00,472: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-07 21:14:00,538: ERROR: main: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B28DAE3310>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
Traceback (most recent call last):
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001B28DAE3310>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\adapters.py", line 644, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B28DAE3310>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 12, in <module>
    data_ingestion.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_pipeline.py", line 14, in main
    data_ingestion.download_file()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\data_ingestion.py", line 32, in download_file
    raise e
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\data_ingestion.py", line 27, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\adapters.py", line 677, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B28DAE3310>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))
[2025-10-07 21:14:59,794: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-07 21:14:59,806: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 21:14:59,817: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 21:14:59,831: INFO: common: created directory at: artifacts]
[2025-10-07 21:14:59,849: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 21:14:59,924: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-07 21:15:00,100: ERROR: main: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023C12E52250>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
Traceback (most recent call last):
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000023C12E52250>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\adapters.py", line 644, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023C12E52250>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 12, in <module>
    data_ingestion.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_pipeline.py", line 14, in main
    data_ingestion.download_file()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\data_ingestion.py", line 32, in download_file
    raise e
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\data_ingestion.py", line 27, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\requests\adapters.py", line 677, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023C12E52250>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))
[2025-10-07 21:17:14,286: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-07 21:17:14,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 21:17:14,303: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 21:17:14,305: INFO: common: created directory at: artifacts]
[2025-10-07 21:17:14,308: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 21:17:14,310: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-07 21:17:38,996: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-07 21:17:41,801: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-07 21:17:41,807: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-07 21:17:41,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 21:17:41,832: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 21:17:41,837: INFO: common: created directory at: artifacts]
[2025-10-07 21:17:41,839: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 21:17:44,607: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 21:17:46,761: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-07 21:17:46,762: INFO: main: *******************]
[2025-10-07 21:17:46,763: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-07 21:17:46,772: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 21:17:46,782: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 21:17:46,794: INFO: common: created directory at: artifacts]
[2025-10-07 21:17:46,801: INFO: common: created directory at: artifacts\training]
[2025-10-07 21:22:12,143: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-07 21:22:12,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 21:22:12,159: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 21:22:12,160: INFO: common: created directory at: artifacts]
[2025-10-07 21:22:12,162: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 21:22:12,164: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-07 21:22:33,164: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-07 21:22:35,781: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-07 21:22:35,786: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-07 21:22:35,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 21:22:35,838: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 21:22:35,843: INFO: common: created directory at: artifacts]
[2025-10-07 21:22:35,848: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 21:22:39,067: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 21:22:40,184: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-07 21:22:40,186: INFO: main: *******************]
[2025-10-07 21:22:40,187: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-07 21:22:40,195: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-07 21:22:40,204: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 21:22:40,212: INFO: common: created directory at: artifacts]
[2025-10-07 21:22:40,214: INFO: common: created directory at: artifacts\training]
[2025-10-07 21:36:57,509: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-07 21:37:03,708: INFO: builder_impl: Assets written to: artifacts\training\assets]
[2025-10-07 21:37:04,152: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-08 19:15:17,516: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-08 19:15:17,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-08 19:15:17,563: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-08 19:15:17,565: INFO: common: created directory at: artifacts]
[2025-10-08 19:15:17,568: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-08 19:15:17,571: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-08 19:15:41,462: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-08 19:15:44,808: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-08 19:15:44,848: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-08 19:15:44,898: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-08 19:15:44,958: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-08 19:15:44,980: INFO: common: created directory at: artifacts]
[2025-10-08 19:15:45,023: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-08 19:15:48,662: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-08 19:15:49,699: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-08 19:15:49,701: INFO: main: *******************]
[2025-10-08 19:15:49,703: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-08 19:15:49,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-08 19:15:49,729: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-08 19:15:49,737: INFO: common: created directory at: artifacts]
[2025-10-08 19:15:49,744: INFO: common: created directory at: artifacts\training]
[2025-10-08 19:33:17,354: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-08 21:00:57,965: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-08 21:00:58,011: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-08 21:00:58,018: INFO: common: created directory at: artifacts]
[2025-10-08 21:03:13,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-08 21:03:13,898: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-08 21:03:13,904: INFO: common: created directory at: artifacts]
[2025-10-08 21:08:18,242: INFO: common: json file saved at: scores.json]
[2025-10-08 21:08:28,205: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-08 21:08:32,825: INFO: builder_impl: Assets written to: C:\Users\MANN\AppData\Local\Temp\tmpuha9ryuk\model\data\model\assets]
[2025-10-08 21:29:11,847: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-08 21:29:11,860: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-08 21:29:11,866: INFO: common: created directory at: artifacts]
[2025-10-08 21:36:39,267: INFO: common: json file saved at: scores.json]
[2025-10-08 21:36:50,461: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-08 21:36:54,551: INFO: builder_impl: Assets written to: C:\Users\MANN\AppData\Local\Temp\tmpmiez5ty9\model\data\model\assets]
[2025-10-08 21:45:53,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-08 21:45:53,236: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-08 21:45:53,246: INFO: common: created directory at: artifacts]
[2025-10-08 21:51:08,026: INFO: common: json file saved at: scores.json]
[2025-10-08 21:51:18,511: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-08 21:51:22,019: INFO: builder_impl: Assets written to: C:\Users\MANN\AppData\Local\Temp\tmpn92_izgh\model\data\model\assets]
[2025-10-09 00:23:05,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 00:23:05,476: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 00:23:05,485: INFO: common: created directory at: artifacts]
[2025-10-09 00:31:48,434: INFO: common: json file saved at: scores.json]
[2025-10-09 00:32:05,469: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-09 00:32:11,064: INFO: builder_impl: Assets written to: C:\Users\MANN\AppData\Local\Temp\tmpagtb8mjv\model\data\model\assets]
[2025-10-09 00:40:09,764: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 00:40:09,783: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 00:40:09,791: INFO: common: created directory at: artifacts]
[2025-10-09 00:49:01,843: INFO: common: json file saved at: scores.json]
[2025-10-09 00:49:17,556: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-09 00:49:24,545: INFO: builder_impl: Assets written to: C:\Users\MANN\AppData\Local\Temp\tmpoaq2tvoa\model\data\model\assets]
[2025-10-09 12:03:49,160: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 12:03:49,201: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 12:03:49,209: INFO: common: created directory at: artifacts]
[2025-10-09 12:14:45,446: INFO: common: json file saved at: scores.json]
[2025-10-09 12:15:07,429: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-09 12:15:15,321: INFO: builder_impl: Assets written to: C:\Users\MANN\AppData\Local\Temp\tmp0ou9f09l\model\data\model\assets]
[2025-10-09 12:25:50,365: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 12:25:50,383: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 12:25:50,397: INFO: common: created directory at: artifacts]
[2025-10-09 12:36:51,666: INFO: common: json file saved at: scores.json]
[2025-10-09 12:37:19,532: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-09 12:37:24,846: INFO: builder_impl: Assets written to: C:\Users\MANN\AppData\Local\Temp\tmp095gr39b\model\data\model\assets]
[2025-10-09 14:09:33,005: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-09 14:09:33,049: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:09:33,055: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:09:33,057: INFO: common: created directory at: artifacts]
[2025-10-09 14:09:33,059: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 14:09:33,062: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 14:09:50,714: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 14:09:55,064: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-09 14:09:55,082: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-09 14:09:55,139: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:09:55,254: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:09:55,322: INFO: common: created directory at: artifacts]
[2025-10-09 14:09:55,389: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 14:09:58,825: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 14:10:00,949: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-09 14:10:00,950: INFO: main: *******************]
[2025-10-09 14:10:00,951: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-09 14:10:00,959: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:10:00,968: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:10:00,977: INFO: common: created directory at: artifacts]
[2025-10-09 14:10:00,986: INFO: common: created directory at: artifacts\training]
[2025-10-09 14:25:53,661: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-09 14:25:53,663: INFO: main: *******************]
[2025-10-09 14:25:53,664: INFO: main: >>>>>>>>Stage Evaluation started<<<<<<<<<<<]
[2025-10-09 14:25:53,675: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:25:53,685: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:25:53,688: INFO: common: created directory at: artifacts]
[2025-10-09 14:25:53,696: ERROR: main: No file or directory found at artifacts/training/model.h5]
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 49, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_pipeline.py", line 13, in main
    evaluation.evaluation()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 44, in evaluation
    self.model = self.load_model(self.config.path_of_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 40, in load_model
    return tf.keras.models.load_model(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts/training/model.h5
[2025-10-09 14:37:54,742: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-09 14:37:54,750: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:37:54,755: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:37:54,758: INFO: common: created directory at: artifacts]
[2025-10-09 14:37:54,760: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 14:37:54,762: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 14:38:12,746: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 14:38:14,805: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-09 14:38:14,807: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-09 14:38:14,815: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:38:14,824: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:38:14,833: INFO: common: created directory at: artifacts]
[2025-10-09 14:38:14,836: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 14:38:17,386: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 14:38:20,142: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-09 14:38:20,143: INFO: main: *******************]
[2025-10-09 14:38:20,144: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-09 14:38:20,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:38:20,159: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:38:20,161: INFO: common: created directory at: artifacts]
[2025-10-09 14:38:20,164: INFO: common: created directory at: artifacts\training]
[2025-10-09 14:38:22,741: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 36, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_03_pipeline.py", line 14, in main
    training.train_valid_generator()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-10-09 14:39:32,398: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-09 14:39:32,406: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:39:32,413: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:39:32,416: INFO: common: created directory at: artifacts]
[2025-10-09 14:39:32,419: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 14:39:32,422: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 14:39:59,668: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 14:40:02,041: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-09 14:40:02,044: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-09 14:40:02,052: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:40:02,063: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:40:02,068: INFO: common: created directory at: artifacts]
[2025-10-09 14:40:02,070: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 14:40:03,661: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 14:40:04,517: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-09 14:40:04,518: INFO: main: *******************]
[2025-10-09 14:40:04,519: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-09 14:40:04,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:40:04,533: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:40:04,536: INFO: common: created directory at: artifacts]
[2025-10-09 14:40:04,541: INFO: common: created directory at: artifacts\training]
[2025-10-09 14:52:58,831: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-09 14:53:02,874: INFO: builder_impl: Assets written to: artifacts\training\assets]
[2025-10-09 14:53:03,284: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-09 14:53:03,290: INFO: main: *******************]
[2025-10-09 14:53:03,293: INFO: main: >>>>>>>>Stage Evaluation started<<<<<<<<<<<]
[2025-10-09 14:53:03,314: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 14:53:03,324: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 14:53:03,329: INFO: common: created directory at: artifacts]
[2025-10-09 14:53:03,332: ERROR: main: No file or directory found at artifacts/training/model.h5]
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 49, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_pipeline.py", line 13, in main
    evaluation.evaluation()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 44, in evaluation
    self.model = self.load_model(self.config.path_of_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 40, in load_model
    return tf.keras.models.load_model(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts/training/model.h5
[2025-10-09 16:38:53,853: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-09 16:38:53,894: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 16:38:53,902: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 16:38:53,904: INFO: common: created directory at: artifacts]
[2025-10-09 16:38:53,906: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 16:38:53,907: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 16:39:19,243: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 16:39:22,115: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-09 16:39:22,119: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-09 16:39:22,130: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 16:39:22,138: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 16:39:22,142: INFO: common: created directory at: artifacts]
[2025-10-09 16:39:22,144: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 16:39:24,577: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 16:39:25,828: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-09 16:39:25,830: INFO: main: *******************]
[2025-10-09 16:39:25,831: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-09 16:39:25,840: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 16:39:25,848: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 16:39:25,857: INFO: common: created directory at: artifacts]
[2025-10-09 16:39:25,860: INFO: common: created directory at: artifacts\training]
[2025-10-09 16:52:29,027: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-09 16:52:29,029: INFO: main: *******************]
[2025-10-09 16:52:29,092: INFO: main: >>>>>>>>Stage Evaluation started<<<<<<<<<<<]
[2025-10-09 16:52:29,101: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 16:52:29,109: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 16:52:29,199: INFO: common: created directory at: artifacts]
[2025-10-09 16:52:29,205: ERROR: main: No file or directory found at artifacts/training/model.h5]
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 49, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_pipeline.py", line 13, in main
    evaluation.evaluation()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 44, in evaluation
    self.model = self.load_model(self.config.path_of_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 40, in load_model
    return tf.keras.models.load_model(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts/training/model.h5
[2025-10-09 17:19:47,220: INFO: main: *******************]
[2025-10-09 17:19:47,221: INFO: main: >>>>>>>>Stage Evaluation started<<<<<<<<<<<]
[2025-10-09 17:19:47,232: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 17:19:47,240: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 17:19:47,244: INFO: common: created directory at: artifacts]
[2025-10-09 17:19:49,559: ERROR: main: name 'model' is not defined]
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 49, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_pipeline.py", line 13, in main
    evaluation.evaluation()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 46, in evaluation
    self.score = model.evaluate(self.valid_generator)
                 ^^^^^
NameError: name 'model' is not defined
[2025-10-09 17:22:52,353: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-09 17:22:52,363: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 17:22:52,370: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 17:22:52,371: INFO: common: created directory at: artifacts]
[2025-10-09 17:22:52,373: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 17:22:52,375: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 17:23:10,941: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 17:23:13,165: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-09 17:23:13,167: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-09 17:23:13,175: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 17:23:13,183: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 17:23:13,186: INFO: common: created directory at: artifacts]
[2025-10-09 17:23:13,188: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 17:23:15,071: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 17:23:16,484: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-09 17:23:16,485: INFO: main: *******************]
[2025-10-09 17:23:16,486: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-09 17:23:16,495: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 17:23:16,503: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 17:23:16,510: INFO: common: created directory at: artifacts]
[2025-10-09 17:23:16,513: INFO: common: created directory at: artifacts\training]
[2025-10-09 17:36:42,814: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-09 17:36:48,436: INFO: builder_impl: Assets written to: artifacts\training\assets]
[2025-10-09 17:36:48,821: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-09 17:36:48,822: INFO: main: *******************]
[2025-10-09 17:36:48,823: INFO: main: >>>>>>>>Stage Evaluation started<<<<<<<<<<<]
[2025-10-09 17:36:48,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 17:36:48,843: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 17:36:48,849: INFO: common: created directory at: artifacts]
[2025-10-09 17:36:48,852: ERROR: main: No file or directory found at artifacts/training/model.h5]
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 49, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_pipeline.py", line 13, in main
    evaluation.evaluation()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 44, in evaluation
    self.model = self.load_model(self.config.path_of_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 40, in load_model
    return tf.keras.models.load_model(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts/training/model.h5
[2025-10-09 18:07:26,078: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-09 18:07:26,115: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 18:07:26,124: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 18:07:26,128: INFO: common: created directory at: artifacts]
[2025-10-09 18:07:26,143: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 18:07:26,145: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 18:07:45,349: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 18:07:47,866: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-09 18:07:47,868: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-09 18:07:47,876: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 18:07:47,884: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 18:07:47,888: INFO: common: created directory at: artifacts]
[2025-10-09 18:07:47,890: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 18:07:50,632: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 18:07:52,104: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-09 18:07:52,106: INFO: main: *******************]
[2025-10-09 18:07:52,107: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-09 18:07:52,115: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 18:07:52,124: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 18:07:52,126: INFO: common: created directory at: artifacts]
[2025-10-09 18:07:52,129: INFO: common: created directory at: artifacts\training]
[2025-10-09 18:25:18,190: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-09 18:25:18,194: INFO: main: *******************]
[2025-10-09 18:25:18,196: INFO: main: >>>>>>>>Stage Evaluation started<<<<<<<<<<<]
[2025-10-09 18:25:18,205: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 18:25:18,220: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 18:25:18,229: INFO: common: created directory at: artifacts]
[2025-10-09 18:25:18,251: ERROR: main: No file or directory found at artifacts/training/model.h5]
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 49, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_pipeline.py", line 13, in main
    evaluation.evaluation()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 44, in evaluation
    self.model = self.load_model(self.config.path_of_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 40, in load_model
    return tf.keras.models.load_model(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts/training/model.h5
[2025-10-09 18:46:26,819: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-09 18:46:26,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 18:46:26,843: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 18:46:26,847: INFO: common: created directory at: artifacts]
[2025-10-09 18:46:26,856: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 18:46:26,859: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 18:46:47,586: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 18:46:50,048: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-09 18:46:50,053: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-09 18:46:50,075: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 18:46:50,087: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 18:46:50,094: INFO: common: created directory at: artifacts]
[2025-10-09 18:46:50,111: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 18:46:54,458: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 18:46:55,976: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-09 18:46:55,977: INFO: main: *******************]
[2025-10-09 18:46:55,978: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-09 18:46:55,989: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 18:46:55,997: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 18:46:56,002: INFO: common: created directory at: artifacts]
[2025-10-09 18:46:56,073: INFO: common: created directory at: artifacts\training]
[2025-10-09 19:03:32,102: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-09 19:03:36,894: INFO: builder_impl: Assets written to: artifacts\training\assets]
[2025-10-09 19:03:37,245: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-09 19:03:37,247: INFO: main: *******************]
[2025-10-09 19:03:37,248: INFO: main: >>>>>>>>Stage Evaluation started<<<<<<<<<<<]
[2025-10-09 19:03:37,274: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 19:03:37,299: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 19:03:37,312: INFO: common: created directory at: artifacts]
[2025-10-09 19:03:37,375: ERROR: main: No file or directory found at artifacts/training/model.h5]
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 49, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_pipeline.py", line 13, in main
    evaluation.evaluation()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 44, in evaluation
    self.model = self.load_model(self.config.path_of_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 40, in load_model
    return tf.keras.models.load_model(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\MANN\miniconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts/training/model.h5
[2025-10-09 19:22:41,714: INFO: main: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-09 19:22:41,749: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 19:22:41,757: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 19:22:41,759: INFO: common: created directory at: artifacts]
[2025-10-09 19:22:41,761: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 19:22:41,764: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 19:23:01,226: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-09 19:23:03,379: INFO: main: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-09 19:23:03,387: INFO: main: >>>>>>>>Stage {STAGE_NAME} started<<<<<<<<<<<]
[2025-10-09 19:23:03,398: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 19:23:03,437: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 19:23:03,443: INFO: common: created directory at: artifacts]
[2025-10-09 19:23:03,462: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-09 19:23:06,206: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 19:23:07,925: INFO: main: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-09 19:23:07,931: INFO: main: *******************]
[2025-10-09 19:23:07,932: INFO: main: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-09 19:23:07,942: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 19:23:07,964: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 19:23:07,968: INFO: common: created directory at: artifacts]
[2025-10-09 19:23:07,972: INFO: common: created directory at: artifacts\training]
[2025-10-09 19:37:44,919: INFO: main: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-09 19:37:44,926: INFO: main: *******************]
[2025-10-09 19:37:44,927: INFO: main: >>>>>>>>Stage Evaluation started<<<<<<<<<<<]
[2025-10-09 19:37:44,949: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 19:37:44,958: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 19:37:44,962: INFO: common: created directory at: artifacts]
[2025-10-09 19:37:47,452: ERROR: main: name 'model' is not defined]
Traceback (most recent call last):
  File "E:\Immediate watch\September\end to end DEEP learning Kindey project\CodeME\Kidney-Disease-Classification-MLFLOW-DVC\main.py", line 49, in <module>
    model_trainer.main()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_pipeline.py", line 13, in main
    evaluation.evaluation()
  File "e:\immediate watch\september\end to end deep learning kindey project\codeme\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 46, in evaluation
    self.score = model.evaluate(self.valid_generator)
                 ^^^^^
NameError: name 'model' is not defined
[2025-10-09 19:41:41,345: INFO: main: *******************]
[2025-10-09 19:41:41,380: INFO: main: >>>>>>>>Stage Evaluation started<<<<<<<<<<<]
[2025-10-09 19:41:41,390: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 19:41:41,398: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 19:41:41,402: INFO: common: created directory at: artifacts]
[2025-10-09 19:46:46,055: INFO: common: json file saved at: scores.json]
[2025-10-09 19:46:59,054: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-09 19:47:02,471: INFO: builder_impl: Assets written to: C:\Users\MANN\AppData\Local\Temp\tmprdpheu7t\model\data\model\assets]
[2025-10-09 19:47:54,064: INFO: main: >>>>>>>>Stage Evaluation completed<<<<<<<<<<<<

x==========x]
[2025-10-10 09:49:53,420: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-10 09:49:53,491: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 09:49:53,497: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 09:49:53,499: INFO: common: created directory at: artifacts]
[2025-10-10 09:49:53,501: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-10 09:49:53,502: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 09:50:13,067: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 09:50:15,141: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-10 09:57:59,251: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-10 09:57:59,258: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 09:57:59,266: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 09:57:59,267: INFO: common: created directory at: artifacts]
[2025-10-10 09:57:59,270: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-10 09:57:59,272: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 09:58:18,125: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 09:58:20,400: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-10 10:01:06,033: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-10 10:01:06,041: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 10:01:06,048: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 10:01:06,050: INFO: common: created directory at: artifacts]
[2025-10-10 10:01:06,052: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-10 10:01:06,054: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 10:01:26,907: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 10:01:29,189: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-10 10:02:13,678: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-10 10:02:13,686: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 10:02:13,692: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 10:02:13,694: INFO: common: created directory at: artifacts]
[2025-10-10 10:02:13,697: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-10 10:02:13,700: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 10:02:31,386: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 10:02:33,948: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-10 12:22:16,313: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-10 12:22:16,339: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 12:22:16,346: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 12:22:16,348: INFO: common: created directory at: artifacts]
[2025-10-10 12:22:16,349: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-10 12:22:16,351: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 12:22:45,064: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 12:22:47,127: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-10 12:27:25,882: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-10 12:27:25,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 12:27:25,898: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 12:27:25,899: INFO: common: created directory at: artifacts]
[2025-10-10 12:27:25,902: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-10 12:27:25,903: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 12:27:46,722: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 12:27:48,929: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-10 12:37:40,859: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage started <<<<<<<]
[2025-10-10 12:37:40,868: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 12:37:40,873: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 12:37:40,875: INFO: common: created directory at: artifacts]
[2025-10-10 12:37:40,876: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-10 12:37:40,878: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 12:38:02,847: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-10 12:38:05,692: INFO: stage_01_data_ingestion: >>>>>>Stage Data Ingestion Stage completed <<<<<<<

x==========x]
[2025-10-10 12:38:53,986: INFO: stage_02_prepare_base_model: >>>>>>>>Stage Prepare Base Model  started<<<<<<<<<<<]
[2025-10-10 12:38:53,994: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 12:38:54,002: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 12:38:54,004: INFO: common: created directory at: artifacts]
[2025-10-10 12:38:54,007: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-10 12:38:56,128: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-10 12:38:56,937: INFO: stage_02_prepare_base_model: >>>>>>>>Stage Prepare Base Model  completed<<<<<<<<<<<<

x==========x]
[2025-10-10 12:39:22,515: INFO: stage_03_model_training: *******************]
[2025-10-10 12:39:22,516: INFO: stage_03_model_training: >>>>>>>>Stage Training started<<<<<<<<<<<]
[2025-10-10 12:39:22,524: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 12:39:22,530: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 12:39:22,532: INFO: common: created directory at: artifacts]
[2025-10-10 12:39:22,535: INFO: common: created directory at: artifacts\training]
[2025-10-10 12:54:31,621: INFO: stage_03_model_training: >>>>>>>>Stage Training completed<<<<<<<<<<<<

x==========x]
[2025-10-10 12:55:10,973: INFO: stage_04_model_evaluation: *******************]
[2025-10-10 12:55:10,975: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation started <<<<<<]
[2025-10-10 12:55:10,982: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-10 12:55:10,989: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-10 12:55:10,996: INFO: common: created directory at: artifacts]
[2025-10-10 13:00:03,130: INFO: common: json file saved at: scores.json]
[2025-10-10 13:00:16,252: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-10-10 13:00:19,690: INFO: builder_impl: Assets written to: C:\Users\MANN\AppData\Local\Temp\tmp8_d4hp3k\model\data\model\assets]
[2025-10-10 13:01:05,574: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation completed <<<<<<

x==========x]
